### PR TITLE
Include equipment not just weapons for the list of equiped weapons

### PR DESCRIPTION
**Pull request by naesean**
This is to support equipment, such as a shield, that also has an attack action, e.g. Shield Bash.

### CODE REVIEW

**Comment by naesean** [comment]
@akrigline I'm not sure how this will behave with equipment that doesn't have a defined action. I assume it would be the same if you have a weapon misconfigured with no action.

**Comment by akrigline** [comment]
> @akrigline I'm not sure how this will behave with equipment that doesn't have a defined action. I assume it would be the same if you have a weapon misconfigured with no action.

Oh that's a good thought and very much an oversight. I'll be sure to double check that and probably end up filtering the `equippedWeapons` based on that. Big thanks for your contribution!

**Comment by naesean** [comment]
Happy to help! It looks like it puts the item in the Special section.

**Comment by akrigline** [comment]
I'll be honest I completely forgot about this. Thanks @naesean, testing now and releasing later today.

**Comment by naesean** [comment]
Awesome! I just tested it on my server and it looks great. Thanks @akrigline!

**Pull request merged**
