### PR TITLE
Fix Item Type labels

### PR DESCRIPTION
**Pull request by kaldigo**

### CODE REVIEW

**Review by akrigline — APPROVED** [review]
Do you happen to know if this works for older core system versions? If not we will need to update the minimum system version compatible

**Comment by kaldigo** [comment]
It has been this way since before 2.0.0 so it should be fine.

**Comment by akrigline** [comment]
big thanks for the PR!

**Comment by akrigline** [comment]
gah, forgot i have more baggage for release creation in this repo than simply releasing on GH, i'll try to get that out today.

**Pull request merged**
